export class Users {
    businessName: string;
    contactFirstName: string;
    contactLastName: string;
    contactMainPhoneNumber: number;
    contactAltPhoneNumber: number;
    contactStreet: string;
    contactCity: string;
    contactState: string;
    contactZip: number;
    employeeFirstName: string;
    employeeLastName: string;
    employeeID: string;
    employeeWorkNumber: number;
    employeeCellNumber: number;
    email: string;
    username: string;
    password: string;
    admin: boolean;
};
